

import java.awt.Graphics;
import java.awt.Image;
import java.util.Properties;
import javax.mail.Session;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JPanel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author monge
 */
public class autenticacion extends javax.swing.JFrame {

    
     static String identificacionNumber = "";
     static String identificacionContrasena="";
     static String email = null;
     static String privilegio = null;
     
 
            
    public autenticacion() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEnviarCodigo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnEntrarInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Correo de gmail");

        btnEnviarCodigo.setText("Enviar Codigo");
        btnEnviarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo de verificacion");

        btnEntrarInicio.setText("Entrar");
        btnEntrarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEnviarCodigo)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnEntrarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarCodigo)
                    .addComponent(btnEntrarInicio))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//vdssutnokynitcpk contrasena
    public void consulta(String usuario) throws SQLException{
        inicio in = new inicio();
        System.out.println("entro al metodo colsulta");
         //String identificacion = null;
         //in.variables(identificacion)=identificacionContrasena =;
         identificacionContrasena = in.variables();
        System.out.println(identificacionContrasena);
        
        
        //select email from personas where password = '1234'
        
        
    }
    
    

    private void btnEnviarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCodigoActionPerformed
    
        inicio in = new inicio();
        System.out.println("entro al metodo colsulta");
         //String identificacion = null;
         //in.variables(identificacion)=identificacionContrasena =;
         identificacionContrasena = in.variables();
        System.out.println(identificacionContrasena);
        
        
        System.out.println("preciona el boto");
         int number;
         String finalNumber = "";
 
        number = (int)(10000 * Math.random());

        finalNumber = "" + number;

        for(int i = finalNumber.length(); i < 4; i++){
            finalNumber = "0" + finalNumber;
        }
        identificacionNumber=finalNumber;
    
        
       String url2 = "select email, privilegio from personas where password='"+identificacionContrasena+"'";
        System.out.println(url2);
         try {
             System.out.println("entro al try");
             Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(url2);
            ResultSet rs;
             rs = ps.executeQuery();
              if(rs.next()){
                  System.out.println("entro al if de email");
                  System.out.println(rs.getString("email"));
                  email = rs.getString("email");
                privilegio = rs.getString("privilegio");
              }
             
         } catch (SQLException ex) {
             System.out.println("entro al catch");
             System.out.println(ex.toString());
         }
             
      

        // Configuración de las propiedades del sistema para establecer la conexión SMTP
      Properties props = new Properties();
      props.put("mail.smtp.host", "smtp.gmail.com");
      props.put("mail.smtp.starttls.enable", "true");
      props.put("mail.smtp.socketFactory.port", "587");
      props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
      props.setProperty("mail.smtp.ssl.protocols", "TLSv1.2");
      props.put("mail.smtp.auth", "true");
      props.put("mail.smtp.port", "587");

      // Establecer la sesión para la conexión SMTP
      Session session = Session.getDefaultInstance(props,
         new javax.mail.Authenticator() {
            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
               return new javax.mail.PasswordAuthentication("mongelindapaloma@gmail.com", "vdssutnokynitcpk");
            }
         });

      try {
         // Crear el objeto MimeMessage y establecer sus propiedades
         Message message = new MimeMessage(session);
         message.setFrom(new InternetAddress("mongelindapaloma@gmail.com"));
         message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(email));
         message.setSubject("test");
         message.setText("tu codigo de acceso es "+ finalNumber);

         // Enviar el correo
         Transport.send(message);

         JOptionPane.showMessageDialog(null, "EL CORREO SE ENVIO EXITOSAMENTE");

      } catch (MessagingException e) {
         throw new RuntimeException(e);
      }
      setVisible(false);
       
    }//GEN-LAST:event_btnEnviarCodigoActionPerformed

    private void btnEntrarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarInicioActionPerformed
        // TODO add your handling code here:
        String codigoValidacion = (txtCodigo.getText());
        if(codigoValidacion.equals(identificacionNumber)){
            if(privilegio.equals("admin")){
            admin ventanaAdmin = new admin();
                        ventanaAdmin.setVisible(true);
            }else{
              usuario ventanaUsuario = new usuario();
                        ventanaUsuario.setVisible(true);  
            }
        }else{
            JOptionPane.showMessageDialog(null, "EL CODIGO DE VERIFICACION NO ES CORRECTO");
        }
    }//GEN-LAST:event_btnEntrarInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(autenticacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(autenticacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(autenticacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(autenticacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new autenticacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrarInicio;
    private javax.swing.JButton btnEnviarCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables

   
}
